export default {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  INCREASE_ITEM: 'INCREASE_ITEM',
  DECREASE_ITEM: 'DECREASE_ITEM',
  ACTION_GET_SEARCH: 'ACTION_GET_SEARCH',
  ACTION_DO_SEARCH: 'ACTION_DO_SEARCH',
  ACTION_PENDING: 'ACTION_PENDING',
  RECEIVED_TWEETS: 'RECEIVED_TWEETS',
  RECEIVED_ONE_TWEET: 'RECEIVED_ONE_TWEET',
  RECEIVED_SEARCH_RESULTS: 'RECEIVED_SEARCH_RESULTS',
  PERFORM_SEARCH: 'PERFORM_SEARCH',
  RECEIVE_SEARCH_RESULTS: 'RECEIVE_SEARCH_RESULTS',
  INIT_SEARCH: 'INIT_SEARCH'
}
