//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendees_ClassHistory
    {
        public int AttendeeID { get; set; }
        public int RegistrationID { get; set; }
        public int ScheduleID { get; set; }
        public int CourseID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string AuthFirstName { get; set; }
        public string AuthLastName { get; set; }
        public string AuthEmail { get; set; }
        public string Acronym { get; set; }
        public string ClassTitle { get; set; }
        public Nullable<System.DateTime> ClassStart { get; set; }
        public string ClassDates { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<long> BlockSeq { get; set; }
    }
}
