//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int cartSeq { get; set; }
        public string ship_Name { get; set; }
        public string ship_Company { get; set; }
        public string ship_Address1 { get; set; }
        public string ship_Address2 { get; set; }
        public string ship_City { get; set; }
        public string ship_State { get; set; }
        public string ship_Zip { get; set; }
        public string ship_Country { get; set; }
        public string ship_Phone { get; set; }
        public string ship_Email { get; set; }
        public string bill_Name { get; set; }
        public string bill_Company { get; set; }
        public string bill_Address1 { get; set; }
        public string bill_Address2 { get; set; }
        public string bill_City { get; set; }
        public string bill_State { get; set; }
        public string bill_Zip { get; set; }
        public string bill_Country { get; set; }
        public string bill_Phone { get; set; }
        public string bill_Email { get; set; }
        public string bill_Fax { get; set; }
        public Nullable<int> proctorID { get; set; }
        public Nullable<decimal> productTotal { get; set; }
        public Nullable<decimal> salesTax { get; set; }
        public Nullable<decimal> shipCharge { get; set; }
        public Nullable<decimal> orderTotal { get; set; }
        public string payType { get; set; }
        public string poNumber { get; set; }
        public string ccNumber { get; set; }
        public Nullable<int> ccExp_Mo { get; set; }
        public Nullable<int> ccExp_Yr { get; set; }
        public Nullable<int> ccSecurity { get; set; }
        public string ccName { get; set; }
        public string ccZip { get; set; }
        public string ccSubmit { get; set; }
        public string ccResponse { get; set; }
        public Nullable<System.DateTime> postedStamp { get; set; }
        public string createdSite { get; set; }
        public System.DateTime createdStamp { get; set; }
        public Nullable<System.DateTime> filledDate { get; set; }
        public string shipVia { get; set; }
        public string shipTracking { get; set; }
    }
}
