//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class cartLine
    {
        public int lineSeq { get; set; }
        public int cartSeq { get; set; }
        public string lineDesc { get; set; }
        public decimal lineUnitPrice { get; set; }
        public int lineQty { get; set; }
        public decimal lineTotal { get; set; }
        public Nullable<int> lineTaxable { get; set; }
    }
}
