//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORY
    {
        public int CATEGORYID { get; set; }
        public string CATEGORYNAME { get; set; }
        public string DISPLAYNAME { get; set; }
        public int CATEGORYTYPEID { get; set; }
        public int INACTIVE { get; set; }
        public int DISPLAY { get; set; }
        public System.DateTime CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
    
        public virtual CATEGORYTYPE CATEGORYTYPE { get; set; }
    }
}
