//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORYTYPE
    {
        public CATEGORYTYPE()
        {
            this.CATEGORies = new HashSet<CATEGORY>();
        }
    
        public int CATEGORYTYPEID { get; set; }
        public string CATEGORYTYPENAME { get; set; }
        public Nullable<int> TEMPLATEID { get; set; }
        public System.DateTime CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
    
        public virtual ICollection<CATEGORY> CATEGORies { get; set; }
    }
}
