//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_Log
    {
        public int Seq { get; set; }
        public System.DateTime Processed_Date { get; set; }
        public Nullable<int> Cart_ID { get; set; }
        public Nullable<int> Reg_TR_Number { get; set; }
        public string CC_Type { get; set; }
        public string CC_Num { get; set; }
        public Nullable<decimal> CC_Amount { get; set; }
        public string CC_Result { get; set; }
        public string ProcessedFrom { get; set; }
        public Nullable<int> Approval { get; set; }
    }
}
