//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC_Payments
    {
        public int Seq { get; set; }
        public System.DateTime ProcessedDate { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> PaymentAmount { get; set; }
        public string CompanyName { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public string InvoiceDescription { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public Nullable<decimal> AppliedAmount { get; set; }
        public string AppliedReference { get; set; }
    }
}
