//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactID { get; set; }
        public int ContactTypeID { get; set; }
        public string ContactCode { get; set; }
        public string ContactSalutation { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactMiddleName { get; set; }
        public string ContactLastName { get; set; }
        public string ContactSuffix { get; set; }
        public string ContactFullName { get; set; }
        public string ContactTitle { get; set; }
        public string ContactNotes { get; set; }
        public string ContactAirport { get; set; }
        public string ContactSpouseName { get; set; }
        public string ContactKidsNames { get; set; }
        public string IMGContactPhoto { get; set; }
        public int Active { get; set; }
        public int Changed { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public double CreatedMemberID { get; set; }
        public Nullable<int> ModifiedMemberID { get; set; }
    }
}
