//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseInstructor
    {
        public int CourseInstructorID { get; set; }
        public int CourseID { get; set; }
        public int InstructorID { get; set; }
        public short InstructorLevel { get; set; }
        public string Exceptions { get; set; }
        public string CurrentStatus { get; set; }
        public bool LeadTechKnowledge { get; set; }
        public bool LeadCurrDevelop { get; set; }
        public bool LeadEquipment { get; set; }
        public string MngtNotes { get; set; }
        public string PreferredText { get; set; }
    }
}
