//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class COURS
    {
        public int CourseID { get; set; }
        public string CourseTitle { get; set; }
        public string CourseSubtitle { get; set; }
        public int CourseTypeID { get; set; }
        public int CourseTopicID { get; set; }
        public int CourseFormatID { get; set; }
        public double ProductTypeID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string CourseCredits { get; set; }
        public string WebHeading { get; set; }
        public string WebToolTip { get; set; }
        public string CourseTimes { get; set; }
        public string CoursePurpose { get; set; }
        public string WebPageIH { get; set; }
        public string TitlePlain { get; set; }
        public string Acronym { get; set; }
        public string GoogleDesc { get; set; }
        public Nullable<int> CourseTier { get; set; }
        public string CourseReferences { get; set; }
        public string CourseInstructorsDescription { get; set; }
        public string CourseAdditionalInformation { get; set; }
        public string CourseOnSite { get; set; }
        public string CourseGuarantee { get; set; }
        public decimal CourseFee { get; set; }
        public string CourseFeeDescription { get; set; }
        public int Active { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int CreatedMemberID { get; set; }
        public Nullable<double> ModifiedMemberID { get; set; }
        public string WebPage { get; set; }
        public Nullable<short> PlanSort { get; set; }
        public string CertTitle1 { get; set; }
        public string CertTitle2 { get; set; }
        public string PPTLink { get; set; }
        public string BrochureLink { get; set; }
        public string Keywords { get; set; }
        public string RefGuideLink { get; set; }
        public string StudyGuideLink { get; set; }
        public string WorkBookLink { get; set; }
        public Nullable<decimal> InstructorCost { get; set; }
        public Nullable<decimal> MtgRmCost { get; set; }
        public Nullable<decimal> OtherFixedCost { get; set; }
        public Nullable<decimal> PerStudentCost { get; set; }
        public Nullable<decimal> TotalFixedCost { get; set; }
        public string ArloID { get; set; }
        public string ViewUri { get; set; }
        public string RegisterUri { get; set; }
        public string EventCode { get; set; }
    }
}
