//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseRelation
    {
        public int CourseRelationID { get; set; }
        public Nullable<int> OpenID { get; set; }
        public Nullable<int> SimulcastID { get; set; }
        public Nullable<int> LiveOnlineID { get; set; }
        public string EventCode { get; set; }
    }
}
