//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int LocationID { get; set; }
        public int LocationTypeID { get; set; }
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public string LocationNotes { get; set; }
        public string HotelSleepRate { get; set; }
        public string HotelMeetingRate { get; set; }
        public int Active { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int CreatedMemberID { get; set; }
        public Nullable<int> ModifiedMemberID { get; set; }
        public string TimeZone { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFax { get; set; }
        public string ContactEmail { get; set; }
    }
}
