//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        public int MEMBERID { get; set; }
        public string LOGIN { get; set; }
        public int INSTRUCTORID { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> PriceCode { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string PREFIX { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public string MIDDLEINITIAL { get; set; }
        public Nullable<System.DateTime> CREATED { get; set; }
        public Nullable<System.DateTime> MODIFIED { get; set; }
        public string Menu { get; set; }
        public Nullable<int> INACTIVE { get; set; }
        public Nullable<System.DateTime> LOGIN_DATE { get; set; }
        public string FTP_ROOT { get; set; }
        public string FullName { get; set; }
    }
}
