//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnSite
    {
        public int SchID { get; set; }
        public int InvoiceNo { get; set; }
        public string SalesRep { get; set; }
        public string Class { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<short> NumDays { get; set; }
        public string ClassTimes { get; set; }
        public string ClassFormat { get; set; }
        public Nullable<short> NumStudents { get; set; }
        public string TextDesc { get; set; }
        public string TextNotes { get; set; }
        public string ContactName { get; set; }
        public string ContactTitle { get; set; }
        public string ContactCompany { get; set; }
        public string ContactPhone { get; set; }
        public string ContactFax { get; set; }
        public string ContactEmail { get; set; }
        public string AltName { get; set; }
        public string AltTitle { get; set; }
        public string AltPhone { get; set; }
        public string CustomerNotes { get; set; }
        public string Location { get; set; }
        public string NearestAirport { get; set; }
        public string DriveTimeMiles { get; set; }
        public string AreaHotels { get; set; }
        public string Directions { get; set; }
        public string Instructor { get; set; }
        public Nullable<decimal> PriceTotal { get; set; }
        public string Agreement { get; set; }
        public string ClassDates { get; set; }
        public Nullable<bool> Canceled { get; set; }
        public string Shipping { get; set; }
        public string ClassTopics { get; set; }
    }
}
