//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegBillPaymentMethodType
    {
        public int RegBillPaymentMethodTypeID { get; set; }
        public string RegBillPaymentMethodTypeName { get; set; }
        public int Active { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int CreatedMemberID { get; set; }
        public Nullable<int> ModifiedMemberID { get; set; }
    }
}
