//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationAttendeeSchedule
    {
        public int RegAttendeeScheduleID { get; set; }
        public int RegistrationAttendeeID { get; set; }
        public int ScheduleID { get; set; }
    }
}
