//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRATION
    {
        public int RegistrationID { get; set; }
        public string RegPromoCode { get; set; }
        public string RegPromoType { get; set; }
        public string RegPromoDesc { get; set; }
        public string RegReason { get; set; }
        public string RegCompanyName { get; set; }
        public string RegAuthFirstName { get; set; }
        public string RegAuthMiddleName { get; set; }
        public string RegAuthLastName { get; set; }
        public string RegAuthTitle { get; set; }
        public string RegAuthMailCode { get; set; }
        public string RegAuthAddress1 { get; set; }
        public string RegAuthAddress2 { get; set; }
        public string RegAuthCity { get; set; }
        public Nullable<int> RegAuthStateID { get; set; }
        public string RegAuthZipcode { get; set; }
        public string RegAuthPhone { get; set; }
        public string RegAuthPhoneExt { get; set; }
        public string RegAuthFax { get; set; }
        public string RegAuthEmail { get; set; }
        public string RegAuthContactMethod { get; set; }
        public string RegBillFirstName { get; set; }
        public string RegBillMiddleName { get; set; }
        public string RegBillLastName { get; set; }
        public string RegBillTitle { get; set; }
        public string RegBillMailCode { get; set; }
        public string RegBillAddress1 { get; set; }
        public string RegBillAddress2 { get; set; }
        public string RegBillCity { get; set; }
        public int RegBillStateID { get; set; }
        public string RegBillZipcode { get; set; }
        public string RegBillPhone { get; set; }
        public string RegBillPhoneExt { get; set; }
        public string RegBillFax { get; set; }
        public string RegBillEmail { get; set; }
        public string RegBillContactMethod { get; set; }
        public int RegBillPaymentMethodTypeID { get; set; }
        public Nullable<int> RegBillCCTypeID { get; set; }
        public string RegBillCCName { get; set; }
        public string RegBillCCNumber { get; set; }
        public Nullable<int> RegBillCCExpirationMonth { get; set; }
        public Nullable<int> RegBillCCExpirationYear { get; set; }
        public string RegBillCheckNumber { get; set; }
        public string RegBillPONumber { get; set; }
        public Nullable<decimal> RegOrderTotal { get; set; }
        public string RegPayStatus { get; set; }
        public string RegStatus { get; set; }
        public string RegNotes { get; set; }
        public int CartID { get; set; }
        public int Printed { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int CreatedMemberID { get; set; }
        public Nullable<int> ModifiedMemberID { get; set; }
        public string RegTakenBy { get; set; }
        public string RegMethod { get; set; }
        public string Website { get; set; }
        public string RegAuthCountry { get; set; }
        public string RegBillCountry { get; set; }
        public string RegCurrency { get; set; }
        public string OriginalPromo { get; set; }
        public string RegBillCCCVC { get; set; }
        public Nullable<System.DateTime> RegBillPaidDate { get; set; }
        public string PastCustomer { get; set; }
        public Nullable<decimal> RegPaidTotal { get; set; }
        public Nullable<decimal> RegBalanceDue { get; set; }
        public Nullable<System.DateTime> MktgFollowupEmailSent { get; set; }
        public Nullable<long> BlockSeq { get; set; }
    }
}
