//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegistrationAttendee
    {
        public int RegistrationAttendeeID { get; set; }
        public int RegistrationID { get; set; }
        public string RegAttendeeFirstName { get; set; }
        public string RegAttendeeLastName { get; set; }
        public string RegAttendeeTitle { get; set; }
        public string RegAttendeeEmail { get; set; }
        public string RegAttendeeNote { get; set; }
        public string Attendance { get; set; }
        public Nullable<System.DateTime> WebUpdatedDate { get; set; }
        public Nullable<System.DateTime> OfficeUpdatedDate { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public string RegAttendeeMiddleName { get; set; }
        public string RegAttendeeSuffix { get; set; }
        public Nullable<int> Att_Discount { get; set; }
        public Nullable<decimal> CourseFee { get; set; }
        public Nullable<decimal> Att_Price { get; set; }
        public Nullable<decimal> Att_Paid { get; set; }
        public Nullable<decimal> Att_Balance { get; set; }
        public string Notes { get; set; }
        public string LastActionStatus { get; set; }
        public string LastActionFor { get; set; }
        public Nullable<System.DateTime> LastReminderSent { get; set; }
        public Nullable<System.DateTime> ThankYouSent { get; set; }
        public Nullable<bool> CodeSummarized { get; set; }
        public Nullable<long> ML_RcdNbr { get; set; }
        public string Flag { get; set; }
    }
}
