//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleCourseInstructor
    {
        public int ScheduleCourseID { get; set; }
        public int ScheduleID { get; set; }
        public int CourseID { get; set; }
        public int InstructorID { get; set; }
        public Nullable<System.DateTime> AcceptedDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<decimal> CourseFee { get; set; }
        public Nullable<short> PriceCode { get; set; }
        public Nullable<short> InstrStatus { get; set; }
    }
}
