//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCHEDULE
    {
        public int ScheduleID { get; set; }
        public int LocationID { get; set; }
        public int CityID { get; set; }
        public int StateID { get; set; }
        public string ScheduleSeminarNumber { get; set; }
        public Nullable<double> ScheduleSeries { get; set; }
        public System.DateTime ScheduleDate { get; set; }
        public string ScheduleDateDescription { get; set; }
        public Nullable<double> ScheduleDateQuarter { get; set; }
        public string ScheduleDateDays { get; set; }
        public Nullable<System.DateTime> ScheduleDateWeek { get; set; }
        public Nullable<int> ScheduleParentID { get; set; }
        public int Active { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public int CreatedMemberID { get; set; }
        public Nullable<double> ModifiedMemberID { get; set; }
        public int CategoryID { get; set; }
        public string InstructorNotes { get; set; }
        public string ScheduleType { get; set; }
        public Nullable<short> BooksSent { get; set; }
        public Nullable<int> isCanadian { get; set; }
        public string fmp_JobPlan { get; set; }
        public string fmp_JobNum { get; set; }
        public Nullable<short> ScheduleStatus { get; set; }
        public Nullable<short> LocationTentative { get; set; }
        public Nullable<bool> Display_Mktg { get; set; }
        public Nullable<bool> Display_Ops { get; set; }
        public string Ops_Status { get; set; }
    }
}
