//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchList_RegLocation
    {
        public int SchID { get; set; }
        public string Title { get; set; }
        public string PlaceDate { get; set; }
        public Nullable<int> isCanadian { get; set; }
    }
}
