//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seminar_Catalog
    {
        public int SchID { get; set; }
        public Nullable<int> TopicID { get; set; }
        public int StateID { get; set; }
        public Nullable<System.DateTime> WeekOf { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Topic { get; set; }
        public Nullable<long> Parent { get; set; }
        public System.DateTime SchDate { get; set; }
        public string TitlePlain { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public Nullable<int> MonthOf { get; set; }
        public Nullable<int> YearOf { get; set; }
        public string DateDesc { get; set; }
        public Nullable<short> Status { get; set; }
        public Nullable<short> isCanadian { get; set; }
        public string WebPage { get; set; }
        public string WebHeading { get; set; }
        public string WebToolTip { get; set; }
        public string WebPageIH { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public System.Data.Entity.Spatial.DbGeography Coordinates { get; set; }
    }
}
