//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingCart
    {
        public Nullable<int> Cart_ID { get; set; }
        public Nullable<short> att_No { get; set; }
        public Nullable<System.DateTime> Cart_Date { get; set; }
        public Nullable<int> TR_No { get; set; }
        public string CoName { get; set; }
        public string att_FName { get; set; }
        public string att_LName { get; set; }
        public string att_Title { get; set; }
        public string att_Email { get; set; }
        public Nullable<int> Sch_ID { get; set; }
        public string Seminar { get; set; }
        public string sem_Place { get; set; }
        public string promoCode { get; set; }
        public string authFName { get; set; }
        public string authLName { get; set; }
        public string authTitle { get; set; }
        public string authPhone { get; set; }
        public string authEmail { get; set; }
        public string billFName { get; set; }
        public string billLName { get; set; }
        public string billTitle { get; set; }
        public string billPhone { get; set; }
        public string billEmail { get; set; }
        public string payMethod { get; set; }
        public string chkNo { get; set; }
        public string poNo { get; set; }
        public string RefName { get; set; }
        public long RCDSEQ { get; set; }
    }
}
