//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_Errors
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> errDate { get; set; }
        public Nullable<int> realRegID { get; set; }
        public Nullable<int> tempRegSeq { get; set; }
        public Nullable<short> tempAttNo { get; set; }
        public Nullable<int> tempRegID { get; set; }
        public string attFName { get; set; }
        public string attMName { get; set; }
        public string attLName { get; set; }
        public string attSuffix { get; set; }
        public string attTitle { get; set; }
        public string attEmail { get; set; }
        public Nullable<int> attSemID { get; set; }
    }
}
