//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_Reg
    {
        public int reg_SEQ { get; set; }
        public int reg_ID { get; set; }
        public Nullable<System.DateTime> reg_Date { get; set; }
        public Nullable<short> sem_No { get; set; }
        public Nullable<int> sem_SID { get; set; }
        public string sem_Title { get; set; }
        public string sem_Place { get; set; }
        public string sem_FeeName { get; set; }
        public Nullable<decimal> sem_FeeAmt { get; set; }
        public Nullable<short> sem_Qty { get; set; }
        public Nullable<decimal> sem_Total { get; set; }
        public Nullable<decimal> sem_Discount { get; set; }
        public Nullable<int> rcdFinal { get; set; }
        public string discountType { get; set; }
        public string discountDesc { get; set; }
    }
}
