//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_ViewStates
    {
        public long cart_ID { get; set; }
        public int reg_ID { get; set; }
        public System.DateTime cart_DateTime { get; set; }
        public string cart_VS { get; set; }
    }
}
