//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_Att
    {
        public Nullable<long> reg_SEQ { get; set; }
        public Nullable<short> att_No { get; set; }
        public string att_FName { get; set; }
        public string att_LName { get; set; }
        public string att_Title { get; set; }
        public string att_Email { get; set; }
        public Nullable<int> reg_ID { get; set; }
        public string att_MName { get; set; }
        public string att_Suffix { get; set; }
        public Nullable<int> rcdFinal { get; set; }
        public Nullable<long> RCDSEQ { get; set; }
        public Nullable<int> Att_Discount { get; set; }
        public long ID { get; set; }
    }
}
