//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_Cust
    {
        public long ID { get; set; }
        public Nullable<int> reg_ID { get; set; }
        public Nullable<int> reg_Cost { get; set; }
        public string promoCode { get; set; }
        public string promoType { get; set; }
        public string promoDesc { get; set; }
        public string CoName { get; set; }
        public string authFName { get; set; }
        public string authLName { get; set; }
        public string authTitle { get; set; }
        public string authMailCode { get; set; }
        public string authAddr1 { get; set; }
        public string authAddr2 { get; set; }
        public string authCity { get; set; }
        public string authState { get; set; }
        public string authZip { get; set; }
        public string authCountry { get; set; }
        public string authPhone1 { get; set; }
        public string authPhone2 { get; set; }
        public string authPhone3 { get; set; }
        public string authPhoneExt { get; set; }
        public string authFax1 { get; set; }
        public string authFax2 { get; set; }
        public string authFax3 { get; set; }
        public string authEmail { get; set; }
        public string billFName { get; set; }
        public string billLName { get; set; }
        public string billTitle { get; set; }
        public string billMailCode { get; set; }
        public string billAddr1 { get; set; }
        public string billAddr2 { get; set; }
        public string billCity { get; set; }
        public string billState { get; set; }
        public string billZip { get; set; }
        public string billCountry { get; set; }
        public string billPhone1 { get; set; }
        public string billPhone2 { get; set; }
        public string billPhone3 { get; set; }
        public string billPhoneExt { get; set; }
        public string billFax1 { get; set; }
        public string billFax2 { get; set; }
        public string billFax3 { get; set; }
        public string billEmail { get; set; }
        public string ConfTo { get; set; }
        public string payMethod { get; set; }
        public string ccType { get; set; }
        public string ccName { get; set; }
        public string ccNumber { get; set; }
        public Nullable<int> ccMonth { get; set; }
        public Nullable<int> ccYear { get; set; }
        public string ccCVC { get; set; }
        public string chkNo { get; set; }
        public string poNo { get; set; }
        public Nullable<int> rcdFinal { get; set; }
        public string RefName { get; set; }
        public Nullable<int> RefKey { get; set; }
        public string RefCompany { get; set; }
        public string RefFName { get; set; }
        public string RefLName { get; set; }
        public string pDrop1 { get; set; }
        public string pDrop2 { get; set; }
        public string pEntry1 { get; set; }
        public string pEntry2 { get; set; }
        public string regTakenBy { get; set; }
        public string regMethod { get; set; }
        public string CEURelated { get; set; }
        public string CEUEntity { get; set; }
        public string PastCustomer { get; set; }
    }
}
