//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebAccount
    {
        public long PKID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public string EmailAddress { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Title { get; set; }
        public string PhoneNumber { get; set; }
        public string CompanyName { get; set; }
        public string AddressLn1 { get; set; }
        public string AddressLn2 { get; set; }
        public string Country { get; set; }
        public string StateProvince { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string PriorCustomer { get; set; }
        public string Industry { get; set; }
        public string OutsideTrainingFrequency { get; set; }
        public string NbrEmplforTraining { get; set; }
        public string TrainingTopics { get; set; }
    }
}
