//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSignup
    {
        public int rcd_SEQ { get; set; }
        public Nullable<System.DateTime> rcd_Date { get; set; }
        public string Referrer { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string Title { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public string Phone { get; set; }
        public string PhoneExtn { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Interest { get; set; }
        public string PromoCode { get; set; }
        public string PromoType { get; set; }
        public string PromoDesc { get; set; }
        public string PreferredContact { get; set; }
        public Nullable<short> OptIN { get; set; }
        public Nullable<int> Posted { get; set; }
        public Nullable<int> find_CoNo { get; set; }
        public string find_CoText { get; set; }
    }
}
