//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipLookup
    {
        public int Seq { get; set; }
        public string Zipcode { get; set; }
        public string CityName { get; set; }
        public Nullable<int> CityID { get; set; }
        public string StateName { get; set; }
        public string StateAbbrv { get; set; }
        public Nullable<int> StateID { get; set; }
        public string CountryName { get; set; }
        public string CountryCode { get; set; }
    
        public virtual ZipLookup ZipLookup1 { get; set; }
        public virtual ZipLookup ZipLookup2 { get; set; }
        public virtual ZipLookup ZipLookup11 { get; set; }
        public virtual ZipLookup ZipLookup3 { get; set; }
    }
}
