//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSTRUCTOR
    {
        public int InstructorID { get; set; }
        public int MemberID { get; set; }
        public double ContactID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<System.DateTime> InstructorAnniversaryDate { get; set; }
        public string InstructorAvailability { get; set; }
        public string InstructorCredentials { get; set; }
        public short PriceCode { get; set; }
        public string InstructorTeachingExperience { get; set; }
        public string InstructorPubAuthorships { get; set; }
        public string InstructorAgreement { get; set; }
        public string InstructorNotes { get; set; }
        public int Active { get; set; }
        public int Status { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public double CreatedMemberID { get; set; }
        public Nullable<double> ModifiedMemberID { get; set; }
    }
}
