//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPCTrainco.Umbraco.Extensions.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ATI_DevelopmentEntities : DbContext
    {
        public ATI_DevelopmentEntities()
            : base("name=ATI_DevelopmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseFormat> CourseFormats { get; set; }
        public virtual DbSet<COURS> COURSES { get; set; }
        public virtual DbSet<CourseTopic> CourseTopics { get; set; }
        public virtual DbSet<CourseType> CourseTypes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<LocationType> LocationTypes { get; set; }
        public virtual DbSet<SCHEDULE> SCHEDULES { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<INSTRUCTOR> INSTRUCTORS { get; set; }
        public virtual DbSet<SearchList_Category> SearchList_Category { get; set; }
        public virtual DbSet<SearchList_Locations> SearchList_Locations { get; set; }
        public virtual DbSet<SearchList_RegLocation> SearchList_RegLocation { get; set; }
        public virtual DbSet<Seminar_Catalog> Seminar_Catalog { get; set; }
    }
}
